#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'passwordCracker' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING_ARRAY passwords
#  2. STRING loginAttempt
#

def passwordCracker(passwords, loginAttempt):
    # Write your code here
    dead_end = set()
    
    stack = []
    stack.append(([], loginAttempt))
    while stack:
        acc, cur = stack.pop()
        
        if cur == "":
            return acc

        is_dead_end = True
        for password in passwords:
            if cur.startswith(password):
                cur2 = cur[len(password):]
                if cur2 in dead_end:
                    continue
                is_dead_end = False    
                acc2 = acc[:]
                acc2.append(password)
                stack.append((acc2, cur2))
        
        if is_dead_end:
            dead_end.add(cur)
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        passwords = input().rstrip().split()

        loginAttempt = input()

        result = passwordCracker(passwords, loginAttempt)
        
        fptr.write("WRONG PASSWORD"+'\n' if result is None else " ".join(result) + '\n')

    fptr.close()
