#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'prims' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY edges
#  3. INTEGER start
#

def prims(n, edges, start):
    # Write your code here
    def findMinNode(weights,visited,minNode):
        min_weight=sys.maxsize
        for i in range(len(weights)):
            if weights[i]<min_weight and visited[i]==False:
                min_weight=weights[i]
                minNode=i
        return minNode
    
    graph=[[-1 for _ in range(n+1) ]for _ in range(n+1) ]
    for x,y,w in edges:
        graph[x][y]=w
        graph[y][x]=w
    visited=[False]*(n+1)
    weights=[sys.maxsize]*(n+1)
    weights[start]=0
    for i in range(1,n+1):
        u= findMinNode(weights,visited,i)
        visited[u]=True
        for v in range(1,n+1):
            if visited[v]==False and graph[u][v]>=0 and graph[u][v]< weights[v]:
                weights[v]=graph[u][v]
    return sum(weights[1:])
        
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    edges = []

    for _ in range(m):
        edges.append(list(map(int, input().rstrip().split())))

    start = int(input().strip())

    result = prims(n, edges, start)

    fptr.write(str(result) + '\n')

    fptr.close()
