#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'closestNumbers' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#
from itertools import chain
def closestNumbers(numbers):
    # Write your code here
    numbers.sort()

    min_diff = float('inf')

    pairs = []

    for i in range(len(numbers) - 1):
        diff = numbers[i + 1] - numbers[i]
        if diff < min_diff:
            min_diff = diff
            pairs = [(numbers[i], numbers[i + 1])]  # Start a new list of pairs
        elif diff == min_diff:
            pairs.append((numbers[i], numbers[i + 1]))  # Add pair to the list

    return list(chain.from_iterable(pairs))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
