#!/bin/python3

import math
import os
import random
import re
import sys

n,m=map(int,input().split())
dist_graph=[[math.inf for _ in range(n+1)]for _ in range(n+1)]
for _ in range(m):
    u,v,w=map(int,input().split())
    dist_graph[u][v]=w
for x in range(n+1):
    dist_graph[x][x]=0

for k in range(1,n+1):
    for i in range(1,n+1):
        for j in range(1,n+1):
            dist_graph[i][j]=min(dist_graph[i][j],dist_graph[i][k]+dist_graph[k][j])

q=int(input())
for _ in range(q):
    u,v=map(int,input().split())
    if dist_graph[u][v]==math.inf:
        print(-1)
    else:
        print(dist_graph[u][v])