#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'almostSorted' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def almostSorted(arr):
    # Write your code here
    start=0
    end=0
    for i in range(1,len(arr)):
        if arr[i-1]>arr[i]:
            start=i-1
            break
    else:
        print("yes")
        return
    for i in range(len(arr)-1,0,-1):
        if arr[i]<arr[i-1]:
            end=i
            break
    arr[start],arr[end]=arr[end],arr[start]
    for i in range(1,len(arr)):
        if arr[i-1]>arr[i]:
            break
    else:
        print("yes")
        print("swap",start+1,end+1)
        return
    
    arr[start],arr[end]=arr[end],arr[start]
    arr[start:end+1]=arr[start:end+1][::-1]
    
    for i in range(1,len(arr)):
        if arr[i-1]>arr[i]:
            break
    else:
        print("yes")
        print("reverse",start+1,end+1)
        return
    
    print("no")        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    almostSorted(arr)
